# Generated by Django 3.2 on 2022-06-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_service_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mainapp.group'),
            preserve_default=False,
        ),
    ]
