# Generated by Django 3.2 on 2022-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
