# Generated by Django 3.2 on 2022-06-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_question_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='mainapp.product'),
            preserve_default=False,
        ),
    ]
