# Generated by Django 3.2 on 2022-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_question_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='product',
        ),
        migrations.AddField(
            model_name='question',
            name='product_id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
