# Generated by Django 3.2 on 2022-06-19 18:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_mdmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mission Vission and Values',
                'verbose_name_plural': 'Mission Vission and Values',
            },
        ),
    ]
