# Generated by Django 3.2 on 2022-06-19 19:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_missionvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supply History with image & Project Name.',
                'verbose_name_plural': 'Supply History with image & Project Name.',
            },
        ),
    ]
