# Generated by Django 3.2 on 2022-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Projectfile/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='project/'),
        ),
    ]
