# Generated by Django 3.2 on 2022-06-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_project_attribute_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='attribute_description',
            new_name='project_attribute',
        ),
    ]
