# Generated by Django 3.2 on 2022-06-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productbrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='Productbrochure/')),
            ],
            options={
                'verbose_name': 'Product Brochure',
                'verbose_name_plural': 'Product Brochure',
            },
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profile'},
        ),
    ]
